CREATE TABLE `meduo_user_info` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `username` char(64) DEFAULT NULL,
  `password` char(128) DEFAULT NULL,
  `phone` char(32) DEFAULT NULL,
  `phone_identified` tinyint(4) DEFAULT 0,
  `email` char(128) DEFAULT NULL,
  `appid` char(32) DEFAULT NULL,
  `openid` char(64) DEFAULT NULL,
  `channel` char(32) DEFAULT NULL,
  `nickname` char(128) DEFAULT NULL,
  `sex` tinyint(4) DEFAULT NULL,
  `city` char(16) DEFAULT NULL,
  `province` char(16) DEFAULT NULL,
  `country` char(16) DEFAULT NULL,
  `ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `index_username` (`username`),
  UNIQUE KEY `index_appid_openid` (`appid`,`openid`),
  KEY `index_openid` (`openid`),
  KEY `index_channel` (`channel`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8